// svelte/src/routes/meditations/+page.svelte
<script lang="ts">
  import Meditation from "$lib/Meditation.svelte"

  import { meditations } from "$lib/meditations"

  let selectedTag = $state("All Tags")
  let tags = ["All Tags", ...new Set(meditations.flatMap((meditation) => meditation.tags))]
</script>

<div class="page">
  <div class="filters">
    <select bind:value={selectedTag}>
      {#each tags as tag}
        <option value={tag}>{tag}</option>
      {/each}
    </select>
  </div>

  <div class="meditations">
    {#each meditations as meditation}
      <Meditation
        slug={meditation.slug}
        title={meditation.title}
        duration={meditation.duration}
        tags={meditation.tags}
      />
    {/each}
  </div>
</div>

<style>
  .page {
  }

  select {
    background: var(--background);
    color: var(--text);
  }

  .meditations {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(384px, 1fr));
    gap: 16px;
  }
</style>

// react/src/app/meditations/page.tsx
"use client"

import styles from "./page.module.css"

import Meditation from "@/lib/Meditation"

import { meditations } from "@/lib/meditations"

import { useState } from "react"

let tags = ["All Tags", ...new Set(meditations.flatMap((meditation) => meditation.tags))]

export default function MeditationsPage() {
  const [selectedTag, setSelectedTag] = useState("All Tags")

  function handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
    setSelectedTag(event.target.value)
  }

  return (
    <div className={styles.page}>
      <div className={styles.filters}>
        <select className={styles.select} value={selectedTag} onChange={handleChange}>
          {tags.map((tag) => (
            <option key={tag} value={tag}>
              {tag}
            </option>
          ))}
        </select>
      </div>
      <div className={styles.meditations}>
        {meditations.map((meditation) => (
          <Meditation
            key={meditation.slug}
            slug={meditation.slug}
            title={meditation.title}
            duration={meditation.duration}
            tags={meditation.tags}
          />
        ))}
      </div>
    </div>
  )
}
